/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package de.dfki.iui.mmir.starterkit;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int close=0x7f020000;
        public static final int facebook_icon=0x7f020001;
        public static final int icon=0x7f020002;
    }
    public static final class id {
        public static final int btn_debug=0x7f080000;
    }
    public static final class layout {
        public static final int main=0x7f030000;
    }
    public static final class raw {
        public static final int rawbeep=0x7f050000;
    }
    public static final class string {
        public static final int app_name=0x7f060001;
        public static final int hello=0x7f060000;
    }
    public static final class style {
        /** 
        Theme customizations available in newer API levels can go in
        res/values-vXX/styles.xml, while customizations related to
        backward-compatibility can go here.
    
         */
        public static final int AppBaseTheme=0x7f070000;
        /**  Application theme. 
         */
        public static final int AppTheme=0x7f070001;
    }
    public static final class xml {
        public static final int config=0x7f040000;
    }
}
